spring:
  profiles:
    include: database, api, secret

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  file:
    path: /home/ubuntu/
    name: UTrip.log
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
